import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@EnableAutoConfiguration
@SpringBootApplication
public class MainApplication {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args) {
    	SpringApplication.run(MainApplication.class, args);
    }

}
